### ISSUE TITLE
RunMode 3 Roadmap

### ISSUE THREAD

**Issue by ExHunter** [ExHunter/runmode-issuetracker#1]
TODO List before releasing RunMode3
- [x] Maps loading from Database
- [x] Player handling
  - [x] Automatically add players on joining game to Database
  - [x] Automatically update player name, last seen, etc. on JoinGame
- [x] Basic running system
- [x] Save runs to Database
- [x] Replays
  - [x] record replays
  - [x] make ReplayBot working
  - [x] Play any replays
  - [x] Replays should be loaded from an Database
    - [x] Create new Database on server
    - [x] Rewrite table code to create new tables by maps instead runID
    - [x] Load Replays from that Database instead local files
- [x] Medals support
- [x] time comparison
- [x] Achievements support
- [ ] Versus mode
- [x] Player commands
  - [x] !play
  - [x] !fail
  - [x] !top / !top10 command
  - [x] !top MAP / !top10 MAP command
  - [x] !freerun
  - [x] !search 'map'/'player' TEXT
  - [x] !hnsna, !hnseu, !rmna, !rmeu, !rzal
  - [x] !choosemap MAP
  - [x] !bestrun
  - [x] Queues
    - [x] Add to Queue
    - [x] Remove from Queue
    - [x] View Queue
  - [x] Profiles
    - [x] Medals
    - [x] Quick overview (last Achievement, runs, last join, etc.)
  - [x] Statistics
    - [x] Maps
    - [x] Runs (total)
    - [x] Maximum Achievement Points
    - [x] Players
  - [x] Rankings
    - [ ] Sorted by Runs
    - [x] Sorted by Golds
    - [x] Sorted by Silver
    - [x] Sorted by Bronze
    - Later somewhen: Sorted by average time (minimum runs required)
    - [x] Sorted by Achievement points
  - [x] View Achievements
- [ ] Admin commands
  - EDIT MODE
  - [x] Add a Map
  - [x] Add a Checkpoint
  - [x] Set Checkpoints num
  - [x] Set Laps num
  - [x] Delete a Checkpoint
  - [x] TeleportToMouse command
  - ADMIN MODE
  - [ ] Delete a run
  - [ ] Remove an achievement
  - [ ] Warn system
  - [ ] Ban System
    - [x] Checking for bans
    - [ ] Ban commands
      - [ ] Ban history
      - [ ] Add ban
      - [ ] Remove ban
  - [ ] Mute System
  - [x] Admin Chat
  - [x] Checking HWID
  - [ ] GeoIP Hostname + Location checking
